version: '3.7'

services:
  billpayment_assessment_postgres_db:
    image: 'postgres:latest'
    container_name: 'billpayment_assessment'
    command: postgres -c 'max_connections=1500'
    restart: always
    environment:
      POSTGRES_DB: 'billpayment_assessment'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    tty: true
    volumes:
      - pgdata_billpayment:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432

volumes:
  pgdata_billpayment:
