server:
  port: 9010
spring:
  application:
    name: Payment-service
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5433/shoppy_db

