package com.payment.service.config.security;

public enum Authorities {

    TOKEN_REFRESH,
    PRE_AUTHENTICATED,
    FULLY_AUTHENTICATED,
    CREATE_AUDIT_TRAIL,
    VIEW_AUDIT_TRAIL,
    UPDATE_AUDIT_TRAIL,
    DELETE_AUDIT_TRAIL,

    CREATE_BANK,
    VIEW_BANK,
    UPDATE_BANK,
    DELETE_BANK,

    CREATE_BILLER,
    VIEW_BILLER,
    UPDATE_BILLER,
    DELETE_BILLER,

    CREATE_DEVICE,
    VIEW_DEVICE,
    UPDATE_DEVICE,
    DELETE_DEVICE,

    CREATE_OPERATOR,
    VIEW_OPERATOR,
    UPDATE_OPERATOR,
    DELETE_OPERATOR,

    CREATE_PRODUCT,
    VIEW_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,

    CREATE_SUBSCRIBER,
    APPROVE_SUBSCRIBER,
    VIEW_SUBSCRIBER,
    UPDATE_SUBSCRIBER,
    DELETE_SUBSCRIBER,

    CREATE_TRANSACTION_TYPE,
    VIEW_TRANSACTION_TYPE,
    UPDATE_TRANSACTION_TYPE,
    DELETE_TRANSACTION_TYPE,

    VIEW_TRANSACTION_REPORT,
    VIEW_TRANSACTION_SUMMARY,
    INITIATE_REVERSAL,
    VALIDATE_REVERSAL,
    LINK_BANK_ACCOUNT,
    VALIDATE_LINK_BANK_ACCOUNT,
    VIEW_TRUST_ACCOUNT,
    VIEW_DASHBOARD,
    EXPORT_REPORT,
    VIEW_TRANSACTION,
    CASHOUT,
    CASHIN,
    AIRTIME_TOPUP,
    BALANCE_ENQUIRY,
    BANK_TRANSFER,
    BILL_PAYMENT,
    PAYMENT,
    TRANSFER,
    TRANSFER_COMMISSION,
    REDEEM_REBATE,

    CREATE_USER,
    UPDATE_USER,
    DELETE_USER,
    VIEW_USER,
}
