server:
  port: 9010
spring:
  application:
    name: Payment-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5434/billpayment_assessment
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: billpayment

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0
    user: root
    password: root
    url: jdbc:postgresql://localhost:5434/billpayment_assessment
    schemas: billpayment
    table: flyway_schema_history
  flywayrunner:
    enabled: false
  messaging:
    enabled: true

app:
  security:
    jwt:
      token:
        secret-key: temp-secret-key
        token-secret: secreet
      expiration: 12000000
      header: payment-system
      issuer: payment-access
      private_key: ${JWT_PRIVATE_KEY:/Users/dec/opt/keys/jwt_private_key.pem}
      public_key: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA+SCwm6D1ieqRqe4HvZxnNhC2WGf9CHgBxK1dbbvRYqazjSYK/zrdR8mLsuV67uHu8GplKr4OfAHHe1C13rJVRlqICVen4bWqryarX65b/LsocEOT/OnGRaSAjCsd8SHb+dF20qY+QA/9Vvh+jrbpemDlJe+4mbNuaXim9mm3vHSaXB4cV0rrQa6P7ZWIXsFetfSbjZG0RHGHLnymXIL+l35prZ9WeoSe5apsutFMaYSIcJ6wj4aowjI2mrf/IzVOIZG+YdkrBxWpSnW+qGWEV5+xGb4gaJ4As+BWM3OwhcQyC+PaWXTRM8KxwI2EqlqJZy5rgF/GKVSO6j/tZnCn2M0Oc/fhoNPG/c2ADN8nElLVvR4M4FbtAUmWshLMwSwGdLI53+CTuiIGvx5QXjn0L2i9nIMTabJgEOksSEKWqs0EMcssSqUU4jyas0lUPONdtV8VYLSR0s1qfkWFje6c9PeS5JrzTIWt89UMtbzdbMZd5+vQ7gdZbGTgx4UcDsa5+7dXxZ5M4FB9A7Bpsst9QPNHgtjkTLTnKcbJJil191fKTq6R0fCpVBW0odEIykT9DeN4eHEdf13YzgP/ZcJyQrOVsEl8ZV0Xlo0x7A4CrHc6tu1nxSPbBpIeLWaPl5Hizpyl7C9zttzC3aN5AcgJIIWNVg0XR+rMEVDrl/Y2tPECAwEAAQ==

password:
  validation:
    min-length: 8
    uppercase: false
    numeric: false
    special-characters: false
external:
  service:
    url: https://billerstest.xpresspayments.com:9603/api/v1
api:
  public:
    key: your_public_key_here
  private:
    key: your_private_key_here
